name: Upload Website
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ci-example

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Create AWS directory
        run: mkdir -p ~/.aws


      - name: Configure AWS CLI
        run: |
          echo "[default]" > ~/.aws/config
          echo "region = eu-central-1" >> ~/.aws/config
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" > ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          chmod 600 ~/.aws/credentials

      - name: Deploy to S3 using AWS CLI
        run: |
          aws s3 cp build/ s3://react-gh-action-s3-helen/ --recursive
